const A="assets/";
const days=[
{d:1,date:"9月23日",route:"十堰 → 成都",city:"成都",km:"约805km",time:"10至11小时",elev:"约500m",risk:"高风险",summary:"第一天只做高速转场，不安排正式景点。两名司机固定轮换，成都早睡。",schedule:[["06:30","十堰出发","走福银、十天、京昆方向，午餐在服务区解决。"],["12:30","汉中以西换驾","每2小时停车活动10分钟，避免单人连续驾驶。"],["18:00","抵达成都","加油、补给氧气和常用药，晚餐后尽快休息。"]],sights:[s("剑门关路段","沿途","只做公路地标，不下高速绕行",32.2150337,105.563513)],hotel:h("全季酒店(成都熊猫基地龙潭寺店)","¥350至550/晚","停车便利，作为长途转场后的标准化休息点。","hotel-chengdu.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=119084538"),food:f("酒店早餐厅或附近清淡川菜","¥40至80/人","不吃过辣和过量酒水，为第二天进山留体力。","food-chengdu.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=119084538"),risks:["全天约805km，首日疲劳最容易被低估。","秦岭山区隧道多，雨雾时降低车速。","不得把到成都后的采购拖到深夜。"]},
{d:2,date:"9月24日",route:"成都 → 雅江",city:"雅江",km:"约403km",time:"8至10小时",elev:"约2530m",risk:"高风险",summary:"正式进入G318。折多山只短停，继续下降到雅江住宿，避免第一晚直接睡在高海拔。",schedule:[["07:00","成都出发","经雅安、泸定进入G318。"],["11:30","泸定午餐","泸定桥视时间短停，控制在45分钟内。"],["14:30","翻越折多山","垭口不久留，不跑跳，乘客不适直接下撤。"],["18:30","抵达雅江","补油后入住，观察头痛和睡眠情况。"]],sights:[s("泸定桥","必停","控制游览时间，避免影响夜间到达",29.9144973,102.2302051),s("折多山口","短停","4298m，仅白天短暂停留",30.0743411,101.8040657)],hotel:h("康巴藏驿·花园酒店(雅江318国道店)","¥350至650/晚","G318沿线门店，优先确认停车位和供氧房型。","hotel-yajiang.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134809962"),food:f("酒店餐厅","¥70至120/人","到店用餐更稳妥，避免夜间再开车找店。","food-yajiang.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134809962"),risks:["折多山高于4200m，白天通过也可能诱发高反。","康定至雅江弯多坡陡，雨雪和团雾风险高。","旅游旺季可能堵车，最晚7点前出成都。"]},
{d:3,date:"9月25日",route:"雅江 → 巴塘",city:"巴塘",km:"约304km",time:"7至9小时",elev:"约2580m",risk:"中高风险",summary:"白天会经过理塘和海子山高海拔区域，晚上下降至巴塘。景点只选短停，不在理塘留宿。",schedule:[["07:30","雅江出发","先走天路十八弯，控制拍照时间。"],["11:30","理塘午餐","4014m地区慢走少说话，吃完即走。"],["14:30","姊妹湖短停","根据乘客状态决定是否下车。"],["18:00","抵达巴塘","加满油，检查胎压和刹车。"]],sights:[s("天路十八弯","短停","观景台注意来车和停车安全",29.9984133,100.8800053),s("理塘西城门","路过","高海拔午餐点，不留宿",29.98555,100.2386303),s("海子山姊妹湖","短停","风大温低，不久留",30.2999358,99.5515609)],hotel:h("全季酒店(甘孜巴塘318国道店)","¥400至700/晚","标准化门店，适合入藏前洗衣和休整。","hotel-batang.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=114401686"),food:f("巴塘伙食团","¥50至80/人","公开页面人均约54元，川菜为主，少油少辣。","food-batang.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/120475/14272351.html"),risks:["理塘、海子山长时间处于4000m上下。","高原横风和突然降温明显。","姊妹湖停车区车多，禁止占道拍照。"]},
{d:4,date:"9月26日",route:"巴塘 → 如美",city:"如美镇",km:"约150km",time:"4至6小时",elev:"约2650m",risk:"中风险",summary:"刻意设置的短程适应日。跨金沙江进入西藏后，重点确认车辆、证件和乘客状态。",schedule:[["08:30","巴塘出发","不追求早到，先保证睡眠。"],["10:30","金沙江大桥","按现场要求通行和拍照，不在桥上停车。"],["12:30","芒康补给","午餐、加油，查询次日东达山路况。"],["15:30","抵达如美","下午完整休息，不再加景点。"]],sights:[s("金沙江大桥","关键路段","正式进入西藏，桥面禁止随意停车",29.7672382,99.0093968),s("如美澜沧江峡谷","住宿地","低海拔峡谷休整",29.618,98.351)],hotel:h("芒康江景富氧酒店(如美镇318国道店)","¥350至600/晚","如美镇低海拔住宿，预订时确认弥散供氧是否另收费。","hotel-rume.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134173624"),food:f("酒店餐厅","¥60至100/人","短程日直接店内用餐，减少额外驾驶。","food-rume.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134173624"),risks:["金沙江沿线可能落石，雨后不在山脚久停。","进藏检查点可能排队，证件放在随手位置。","短程日也不能饮酒或剧烈运动。"]},
{d:5,date:"9月27日",route:"如美 → 八宿",city:"八宿",km:"约292km",time:"8至10小时",elev:"约3280m",risk:"高风险",summary:"高海拔翻山与连续下坡集中在同一天。东达山快速通过，怒江72拐必须低挡控速。",schedule:[["06:30","如美出发","早出避开夜间山路。"],["10:30","东达山通过","最高点不久留，随时观察乘客反应。"],["13:00","左贡午餐","检查刹车温度后再进入长下坡。"],["16:00","怒江72拐","低挡控速，禁止空挡滑行。"],["19:00","抵达八宿","入住后不洗过热的澡。"]],sights:[s("东达山","快速通过","约5130m，全程住宿不超4200m不等于白天不超",29.710607,98.00315),s("怒江72拐","关键路段","长下坡低挡控速",30.1300189,97.2867235)],hotel:h("八宿西岸有氧酒店(318国道店)","¥350至650/晚","优先确认供氧、停车和次日早饭时间。","hotel-basu.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=122414366"),food:f("燃木齐藏餐厅(八宿店)","¥60至80/人","公开页面人均约57元，建议提前电话确认营业。","food-basu.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/120403/8058338.html"),risks:["东达山高海拔暴露时间长，高反风险显著。","怒江72拐连续急弯和长下坡，刹车热衰减。","当天到达时间易被施工和车流拉长。"]},
{d:6,date:"9月28日",route:"八宿 → 波密",city:"波密",km:"约217km",time:"5至7小时",elev:"约2750m",risk:"中风险",summary:"里程不长，主要任务是恢复。米堆冰川为可选支线，只在天气、体力和路况都允许时进入。",schedule:[["08:00","八宿出发","先沿G318到然乌湖。"],["09:30","然乌湖","湖边短停，注意低温和横风。"],["11:00","判断是否去米堆","往返支线会增加时间，不舒服就直接去波密。"],["16:30","抵达波密","洗衣、补给、充分睡眠。"]],sights:[s("然乌湖","必停","湖边风大，注意保暖",29.4611273,96.7891431),s("米堆冰川","可选支线","只在路况与体力允许时前往",29.4112642,96.5219417)],hotel:h("桔子酒店(林芝波密县318国道店)","¥400至700/晚","低海拔恢复点，停车和洗衣较方便。","hotel-bomi.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=123340498"),food:f("帅哥餐厅","¥70至110/人","公开页面人均约74元，川藏线常见川菜，避免过辣。","food-bomi.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/108/469093.html"),risks:["然乌至波密雨雾较多，临崖路段能见度下降。","米堆支线增加时间，不能为打卡硬赶。","湖区早晚温差大，防失温。"]},
{d:7,date:"9月29日",route:"波密 → 林芝",city:"林芝",km:"约227km",time:"6至8小时",elev:"约2900m",risk:"中高风险",summary:"通麦之后进入林海，色季拉山仍是高海拔。能否看到南迦巴瓦取决于天气，不为等云开而晚走。",schedule:[["08:00","波密出发","通麦路段保持车距。"],["11:30","鲁朗午餐","石锅鸡需要时间，提前下单。"],["14:00","色季拉山","天气差或身体不适就不下车。"],["17:30","抵达林芝","为次日拉萨行程加油。"]],sights:[s("鲁朗林海","必停","林海观景与午餐合并",29.7547,94.7302),s("色季拉山口","短停","约4555m，天气决定视野",29.6206,94.5869)],hotel:h("林芝工布天街林海公园亚朵酒店","¥500至900/晚","城市住宿条件更好，适合进入拉萨前恢复。","hotel-nyingchi.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=114064746"),food:f("鲁朗翠花特色石锅鸡","¥80至150/人","公开页面不同套餐人均约79至146元，建议2人点小份。","food-lulang.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/108/581936.html"),risks:["通麦雨季落石和积水风险需关注。","色季拉山高海拔、低温和团雾叠加。","石锅鸡等餐时间长，不能压缩后续安全车程。"]},
{d:8,date:"9月30日",route:"林芝 → 拉萨",city:"拉萨",km:"约395km",time:"6至8小时",elev:"约3650m",risk:"中风险",summary:"走林拉高速抵达拉萨。晚间只看布达拉宫夜景，不洗热水澡、不饮酒，让身体先适应。",schedule:[["08:30","林芝出发","优先走林拉高速，按当天导航和管制通行。"],["12:30","服务区午餐","不绕远加景点。"],["16:00","抵达拉萨","入住富氧酒店后休息。"],["19:30","布宫夜景","乘车前往，步行量从小控制。"]],sights:[s("尼洋河风光带","沿途","行车观景，不随意停车",29.5944724,94.4015621),s("米拉山隧道","关键路段","以实际导航通行状态为准",29.8163426,92.334352),s("布达拉宫夜景","短停","第一晚只看夜景",29.657,91.117)],hotel:h("萨吉富氧酒店(布达拉宫店)","¥500至900/晚","连续住2晚，预订时确认弥散供氧和停车条件。","hotel-lhasa.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=118833411"),food:f("吉祥圣雪藏餐","¥80至120/人","公开页面人均约84元，第一晚少量尝试，别吃撑。","food-lhasa.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/36/4617365.html"),risks:["拉萨住宿海拔3650m，第一晚可能出现头痛和失眠。","林拉高速长隧道多，注意限速与车距。","抵达后兴奋性活动会放大高反。"]},
{d:9,date:"10月1日",route:"拉萨全天",city:"拉萨",km:"市内约25km",time:"低强度游览",elev:"约3650m",risk:"中风险",summary:"布达拉宫是当天唯一硬任务，其余按体力删减。预约时间决定全天顺序，禁止临时加纳木错。",schedule:[["08:30","布达拉宫","按预约时段提前到场，缓慢爬楼。"],["12:30","午餐与午休","至少休息1.5小时。"],["15:00","大昭寺和八廓街","走不动就只保留大昭寺外围。"],["18:30","药王山","视体力拍摄布宫，不为机位拥挤硬等。"]],sights:[s("布达拉宫","必停","务必提前预约",29.657,91.117),s("大昭寺","按体力","与八廓街合并游览",29.6528598,91.1317978),s("八廓街","按体力","慢走，不追求全部逛完",29.6521,91.1325),s("药王山观景台","可选","体力不足直接取消",29.6553,91.1188)],hotel:h("萨吉富氧酒店(布达拉宫店)","¥500至900/晚","不换酒店，减少搬运行李和适应压力。","hotel-lhasa.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=118833411"),food:f("吉祥圣雪藏餐","¥80至120/人","提前预约，避免排队过久。","food-lhasa.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/36/4617365.html"),risks:["布达拉宫台阶密集，心率容易快速上升。","国庆首日人流大，预约和交通不确定性高。","任何明显高反都应取消下午行程。"]},
{d:10,date:"10月2日",route:"拉萨 → 那曲 → 索县",city:"索县",km:"约558km",time:"11至13小时",elev:"约3990m",risk:"极高风险",summary:"本方案最关键的高海拔长途日。沿G109至那曲，再转G317到索县，必须天亮出发且双司机严格轮换。",schedule:[["05:30","拉萨出发","前一晚加满油、装好早餐。"],["10:30","那曲补给","评估乘客状态，不适则留那曲就医或下撤，不硬赶。"],["12:00","转入G317","确认索县方向无封路和临时管制。"],["18:30","抵达索县","夜间3990m，入住后静卧观察。"]],sights:[s("那曲草原路段","沿途","只在安全停车点短停",31.48,92.051),s("赞丹寺","路过","时间不足不入内",31.8778642,93.7878447)],hotel:h("雲璟酒店","¥450至750/晚","索县中心住宿，预订时确认供氧与停车。","hotel-suo.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134722248"),food:f("酒店早餐厅或简餐","¥40至70/人","抵达后不再驾车找网红店，清淡少量。","food-suo.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=134722248"),risks:["全日高海拔暴露，索县住宿约3990m。","约558km且车程可能超过12小时，疲劳风险极高。","G317天气、施工和临时管制会显著改变到达时间。","如那曲已明显高反，必须改变计划，不能继续向索县。"]},
{d:11,date:"10月3日",route:"索县 → 丁青",city:"丁青",km:"约246km",time:"7至9小时",elev:"约3850m",risk:"高风险",summary:"里程不长但仍在高海拔北线，弯道、草原天气和道路施工会拉长车程。",schedule:[["08:00","索县出发","确认丁青方向通行后再走。"],["11:30","巴青补给","午餐、加油、观察乘客状态。"],["15:30","丁青入住","不再追加孜珠寺支线。"],["17:00","查杰玛大殿","仅在体力和开放时间允许时前往。"]],sights:[s("巴青草原路段","沿途","风雪或冰雹时立即减速",31.918,94.061),s("查杰玛大殿","可选","到丁青后有体力再去",31.3711967,96.5027489)],hotel:h("唐蕃大酒店","¥350至600/晚","丁青县城住宿，确认供氧和热水时段。","hotel-dingqing.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=116987405"),food:f("唐蕃大酒店餐厅","¥50至80/人","公开门店图显示店内餐饮空间，入住后直接用餐。","food-dingqing.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=116987405"),risks:["连续第二晚接近4000m，累积高反需要重点观察。","北线移动信号和补给密度低于G318。","不加孜珠寺支线，避免砂石山路和时间失控。"]},
{d:12,date:"10月4日",route:"丁青 → 昌都",city:"昌都",km:"约234km",time:"6至8小时",elev:"约3240m",risk:"中高风险",summary:"海拔开始下降，但山路依然不能放松。下午到昌都后，以休息和车辆检查为主。",schedule:[["08:00","丁青出发","先确认沿线施工与管制。"],["12:00","沿途午餐","选择县城或正规餐馆，不在偏僻路边久停。"],["15:30","抵达昌都","检查轮胎、刹车和玻璃水。"],["17:00","强巴林寺","只在体力允许时短游。"]],sights:[s("强巴林寺","可选","昌都市区短游",31.1436119,97.1772311)],hotel:h("昌都通泰明宇丽呈酒店","¥450至750/晚","城市配套较完整，为次日长途做车辆和人员恢复。","hotel-qamdo.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=60616690"),food:f("酒店颐和家宴","¥70至120/人","酒店公开页面列有餐饮空间，减少市区额外驾驶。","food-qamdo.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=60616690"),risks:["丁青至昌都仍有连续弯道和落石区。","海拔下降不代表疲劳消失，午后容易犯困。","次日长途，今晚不得熬夜。"]},
{d:13,date:"10月5日",route:"昌都 → 江达 → 德格 → 甘孜",city:"甘孜县",km:"约509km",time:"11至13小时",elev:"约3390m",risk:"极高风险",summary:"跨金沙江进入四川的长途日。德格只补给和路过，印经院不作为硬任务，核心是天黑前到甘孜。",schedule:[["06:00","昌都出发","早餐打包，尽早进入G317。"],["10:30","江达补给","在县城加油，不把油量拖到德格。"],["13:00","德格午餐","不排队游印经院，按到达时间决定。"],["18:30","抵达甘孜","日落前进城是唯一目标。"]],sights:[s("岗托大桥","关键路段","过金沙江进入四川",31.6257284,98.5907036),s("德格印经院","路过","时间充足才入内",31.80657,98.5804943),s("雀儿山隧道","关键路段","注意隧道限速与明暗适应",31.9284017,98.9242905),s("格萨尔王城","路过","抵达早才短停",31.6063583,100.0100642)],hotel:h("甘孜县王府大酒店(格萨尔王城店)","¥450至800/晚","甘孜县城落脚，预订时确认停车位。","hotel-ganzi.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=128310470"),food:f("康珠藏餐","¥50至80/人","公开页面人均约54至64元，抵达晚则提前电话确认。","food-ganzi.webp","https://gs.ctrip.com/html5/you/foods/fooddetail/120478/7785246.html"),risks:["约509km山路，实际车程可能超过13小时。","昌都至德格施工、落石和临时管制不确定性大。","夜间进入甘孜前可能出现低温和结冰。","德格景点必须让位于到达时间。"]},
{d:14,date:"10月6日",route:"甘孜 → 炉霍 → 马尔康 → 成都",city:"成都",km:"约819km",time:"14至16小时",elev:"约500m",risk:"极高风险",summary:"真实道路估算接近819km，是全程最累的一天。只允许转场，卡萨湖、卓克基和映秀均为路过标注，不安排正式游览。",schedule:[["05:00","甘孜出发","两司机已吃早餐，车辆前夜加满油。"],["08:00","炉霍换驾","短休后继续，不进入支线景区。"],["13:30","马尔康补给","午餐控制在40分钟内。"],["18:00","映秀一带","评估疲劳，必要时汶川或都江堰临时住宿。"],["21:00","抵达成都","只入住，不安排夜宵和游览。"]],sights:[s("卡萨湖","路过","只在安全停车点短停",31.6582771,100.2567368),s("卓克基土司官寨","路过","不入内游览",31.8694677,102.2914204),s("映秀路段","关键路段","进入高速前再次换驾",31.063,103.484)],hotel:h("全季酒店(成都熊猫基地龙潭寺店)","¥400至700/晚","国庆返程期房价可能上浮，优先选择可取消房价。","hotel-chengdu.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=119084538"),food:f("酒店早餐厅或附近简餐","¥40至80/人","到达晚，不再跨城找店。","food-chengdu.webp","https://hotels.ctrip.com/hotels/detail/?hotelId=119084538"),risks:["约819km且大段山路，14至16小时只是正常估算。","这是不可称为轻松的硬赶日，驾驶疲劳是首要风险。","若18点仍未到映秀附近，应在汶川或都江堰止损住宿。","次日必须回十堰，任何延误都会压缩最后一天。"]},
{d:15,date:"10月7日",route:"成都 → 十堰",city:"十堰到家",km:"约800km",time:"10至12小时",elev:"约300m",risk:"高风险",summary:"最后一天仍是高速长途，重点是安全回到十堰。遇国庆返程拥堵，车程可能显著增加。",schedule:[["06:00","成都出发","避开早高峰，前夜准备好食物和水。"],["11:30","广元或汉中换驾","服务区用餐，不出高速绕行景点。"],["16:30","最后一次长休","即使接近十堰也不能连续硬撑。"],["19:00","回到十堰","行程结束，次日再整理车辆和行李。"]],sights:[s("剑门关路段","沿途","不下高速游览",32.2150337,105.563513)],hotel:null,food:f("高速服务区简餐","¥35至60/人","选择热食和清淡主食，避免饱食后犯困。","food-chengdu.webp",""),risks:["国庆末日返程车流大，拥堵和追尾风险上升。","连续第2个800km级长途日，累积疲劳非常明显。","离家越近越容易放松警惕，最后200km必须继续轮换。"]}
];

function h(name,price,note,img,url){return{name,price,note,img:A+img,url}}function f(name,price,note,img,url){return{name,price,note,img:A+img,url}}function s(name,type,note,lat,lon){return{name,type,note,lat,lon}}

const cityPoints=[
{d:"起点",name:"十堰",lat:32.63,lon:110.799},{d:"D1/D14",name:"成都",lat:30.572,lon:104.066},{d:"D2",name:"雅江",lat:30.032,lon:101.014},{d:"D3",name:"巴塘",lat:30.005,lon:99.109},{d:"D4",name:"如美",lat:29.618,lon:98.351},{d:"D5",name:"八宿",lat:30.053,lon:96.918},{d:"D6",name:"波密",lat:29.859,lon:95.768},{d:"D7",name:"林芝",lat:29.648,lon:94.361},{d:"D8/D9",name:"拉萨",lat:29.66,lon:91.132},{d:"D10",name:"那曲",lat:31.48,lon:92.051},{d:"D10",name:"索县",lat:31.885,lon:93.785},{d:"D11",name:"丁青",lat:31.412,lon:95.599},{d:"D12",name:"昌都",lat:31.14,lon:97.172},{d:"D13",name:"江达",lat:31.499,lon:98.218},{d:"D13",name:"德格",lat:31.806,lon:98.581},{d:"D13",name:"甘孜",lat:31.622,lon:100},{d:"D14",name:"炉霍",lat:31.391,lon:100.68},{d:"D14",name:"马尔康",lat:31.905,lon:102.206}
];
const checklist=["身份证、驾驶证、行驶证","布达拉宫预约凭证","离线地图与充电线","两车充或大功率电源","血氧仪与体温计","保暖层、雨具、手套","备胎、补胎液、充气泵","拖车绳与三角警示牌","常用药和个人处方药","饮用水与高热量路餐","现金和多个支付方式","每晚可取消的备用酒店"];
const roads=[{t:"G318进藏段",p:"折多山、东达山、怒江72拐是主要驾驶压力点。高海拔垭口只短停。"},{t:"G317北线段",p:"路况与补给不如G318稳定，每天早晨重新核对管制、施工和天气。"},{t:"D14止损点",p:"甘孜到成都约819km。18点仍未到映秀附近，就在汶川或都江堰住宿，不夜战。"}];

let activeDay=0,map=null,mapReady=false,activeView="day";
const $=id=>document.getElementById(id);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function mediaCard(kind,item){if(!item)return `<div class="aside-section"><h3>住宿</h3><strong>今日回到十堰</strong><p>无住宿消费。</p></div>`;const title=item.url?`<a href="${item.url}" target="_blank" rel="noopener">${esc(item.name)}</a>`:esc(item.name);return `<figure><img src="${item.img}" alt="${esc(item.name)}实景" loading="lazy"><figcaption><span class="kind">${kind}</span><strong>${title}</strong><span class="price">${item.price}</span><p>${item.note}</p></figcaption></figure>`}
function renderDay(i){activeDay=i;const d=days[i];document.querySelectorAll(".day-btn").forEach((b,n)=>b.classList.toggle("active",n===i));$("dateLine").textContent=`D${d.d} ${d.date}`;$("riskChip").textContent=d.risk;$("dayRoute").textContent=d.route;$("daySummary").textContent=d.summary;$("distance").textContent=d.km;$("driveTime").textContent=d.time;$("sleepElev").textContent=d.elev;$("stayCity").textContent=d.city;$("schedule").innerHTML=d.schedule.map(x=>`<div class="stop"><time>${x[0]}</time><div><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join("");$("sightStrip").innerHTML=d.sights.map(x=>`<div class="sight-item"><b><span class="sight-tag">${x.type}</span>${x.name}</b><small>${x.note}</small></div>`).join("");$("hotelReco").innerHTML=mediaCard("住宿推荐",d.hotel);$("foodReco").innerHTML=mediaCard("餐饮推荐",d.food);$("riskList").innerHTML=d.risks.map(x=>`<li>${x}</li>`).join("");$("prevBtn").disabled=i===0;$("nextBtn").disabled=i===days.length-1;document.querySelectorAll(".day-btn")[i]?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}
function build(){
  $("dayNav").innerHTML=days.map((d,i)=>`<button class="day-btn${i===0?" active":""}" data-day="${i}"><b>D${d.d}</b><small>${d.date} ${d.city}</small></button>`).join("");
  $("stayRows").innerHTML=days.map(d=>`<tr><td>D${d.d}<br><small>${d.date}</small></td><td>${d.hotel?tableMedia(d.hotel):"回到十堰，无住宿"}</td><td>${tableMedia(d.food)}</td><td>${d.elev}</td><td class="table-risk"><strong>${d.risk}</strong><br>${d.risks[0]}</td></tr>`).join("");
  $("checklist").innerHTML=checklist.map(x=>`<div class="check">${x}</div>`).join("");$("roadGrid").innerHTML=roads.map(x=>`<div class="road-item"><b>${x.t}</b><p>${x.p}</p></div>`).join("");renderDay(0)
}
function tableMedia(item){const name=item.url?`<a href="${item.url}" target="_blank" rel="noopener">${esc(item.name)}</a>`:esc(item.name);return `<div class="table-media"><img src="${item.img}" alt="${esc(item.name)}实景" loading="lazy"><div><strong>${name}</strong><span class="price">${item.price}</span><small>${item.note}</small></div></div>`}
function switchView(view){activeView=view;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===view));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===view+"View"));if(view==="route")initMap()}

async function initMap(){if(mapReady){setTimeout(()=>map.invalidateSize(),50);return}const status=$("mapStatus");try{
  if(!window.L)throw new Error("地图组件未加载");map=L.map("routeMap",{zoomControl:true,minZoom:4,maxZoom:15});
  const tiles=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
  let tileLoaded=false;tiles.once("load",()=>{tileLoaded=true;status.classList.add("hidden")});
  const res=await fetch("data/route.json");if(!res.ok)throw new Error("道路轨迹文件加载失败");const data=await res.json();
  const inLine=L.geoJSON(data.inbound,{style:{color:"#a61f32",weight:5,opacity:.94}}).addTo(map);const outLine=L.geoJSON(data.return,{style:{color:"#ad8034",weight:5,opacity:.9,dashArray:"8 6"}}).addTo(map);const group=L.featureGroup([inLine,outLine]);
  cityPoints.forEach(p=>{const icon=L.divIcon({className:"",html:`<span class="city-marker">${p.d.replace("D","")}</span>`,iconSize:[26,26],iconAnchor:[13,13]});L.marker([p.lat,p.lon],{icon}).addTo(map).bindPopup(`<b>${p.d} ${p.name}</b><br>行程住宿或关键补给点`).bindTooltip(p.name,{direction:"top"})});
  const seen=new Set();days.forEach(d=>d.sights.forEach(p=>{const key=p.name;if(seen.has(key))return;seen.add(key);const icon=L.divIcon({className:"",html:'<span class="sight-marker"></span>',iconSize:[15,15],iconAnchor:[7,7]});L.marker([p.lat,p.lon],{icon}).addTo(map).bindPopup(`<b>D${d.d} ${p.name}</b><br>${p.type}：${p.note}`).bindTooltip(p.name,{direction:"top"})}));
  map.fitBounds(group.getBounds(),{padding:[24,24]});mapReady=true;setTimeout(()=>{if(!tileLoaded){status.textContent="真实道路轨迹已加载，但OpenStreetMap底图暂时无法连接。请检查网络后刷新。";$("routeFallback").style.display="block"}},7000)
}catch(err){status.textContent=`地图加载失败：${err.message}`;$("routeFallback").style.display="block"}}

function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),1800)}
document.addEventListener("click",e=>{const day=e.target.closest(".day-btn");if(day){switchView("day");renderDay(Number(day.dataset.day));return}const tab=e.target.closest(".tab");if(tab)switchView(tab.dataset.view)});
$("prevBtn").addEventListener("click",()=>renderDay(Math.max(0,activeDay-1)));$("nextBtn").addEventListener("click",()=>renderDay(Math.min(days.length-1,activeDay+1)));$("themeBtn").addEventListener("click",()=>{const dark=document.documentElement.dataset.theme!=="dark";document.documentElement.dataset.theme=dark?"dark":"";$("themeBtn").textContent=dark?"日间":"夜间";localStorage.setItem("g318-theme",dark?"dark":"light")});$("printBtn").addEventListener("click",()=>window.print());
$("shareBtn").addEventListener("click",async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);toast("链接已复制")}}catch(e){if(e.name!=="AbortError")toast("请复制浏览器地址分享")}});$("favBtn").addEventListener("click",()=>{const on=localStorage.getItem("g318-fav")!=="1";localStorage.setItem("g318-fav",on?"1":"0");$("favBtn").textContent=on?"已收藏":"收藏";toast(on?"已收藏到本机":"已取消收藏")});
if(localStorage.getItem("g318-theme")==="dark"){document.documentElement.dataset.theme="dark";$("themeBtn").textContent="日间"}if(localStorage.getItem("g318-fav")==="1")$("favBtn").textContent="已收藏";build();
